id: P009171
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W28928
  title: མཐོ་འབྲིང་གི་བོད་ཀྱི་སྐད་ཡིག་བསླབ་གཞིའི་མིང་ཚིག་འགྲེལ་བཤད
  author: ''
  volumes:
    fc489d72c5c145feaecf27bb76984ea8:
      image_group_id: I4866
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
